name: Publish
on:
  pull_request:
    types: [closed]
    branches:      
      - master

jobs:  
  publish:
    permissions: write-all
    if: github.event.pull_request.merged == true # only trigger on successful PR merge
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # needed for mono repo        

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}'

    - name: "Version and publish"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"        
        npm ci
        npm run publish -- from-git patch --no-push --yes        
