name: Publish
on:
  pull_request:
    types: [closed]
    branches:      
      - master

jobs:  
  publish:
    permissions: write-all
    if: github.event.pull_request.merged == true # only trigger on successful PR merge
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # needed for mono repo        

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}'

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: "Version and publish"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"        
        npm ci
        git checkout -b ${{ steps.extract_branch.outputs.branch }}-PUBLISH
        git push origin ${{ steps.extract_branch.outputs.branch }}-PUBLISH
        npm run publish -- patch --yes        
        
